TOOLCHAIN_HOST_TASK_append = "${SDK_EXTRA_TOOLS}"

SDK_EXTRA_TOOLS = " nativesdk-python-cheetah \
    nativesdk-python-netserver nativesdk-python-pprint \
    nativesdk-python-pickle nativesdk-python-shell \
    nativesdk-python-subprocess nativesdk-python-modules \
    nativesdk-orc nativesdk-swig nativesdk-python-distutils \
    nativesdk-python-xml nativesdk-python-compile \
    nativesdk-cmake nativesdk-python-mako nativesdk-python-six \
    "

SDK_EXTRA_TOOLS_task-populate-sdk-ext = ""

