set( BLAS_F2C_DOUBLE_WORKS_EXITCODE 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( BLAS_F2C_DOUBLE_WORKS_EXITCODE__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)

set( BLAS_F2C_FLOAT_WORKS_EXITCODE 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( BLAS_F2C_FLOAT_WORKS_EXITCODE__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)

set( BLAS_USE_CBLAS_DOT_EXITCODE 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( BLAS_USE_CBLAS_DOT_EXITCODE__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)

